#!/usr/bin/env bash
set -e
set +x

type aws >/dev/null 2>&1 || { echo >&2 "aws cli is required but it is not installed."; exit 1; }
type nslookup >/dev/null 2>&1 || { echo >&2 "nslookup is required but it is not installed."; exit 1; }

# usage
usage () {
  echo "Usage: ${0##*/} [-h|--help] [--sns-topic sns-topic-arn] <domain> <port> <security-group-id>"
  exit 0
}

e() {
    echo "[$(date +%Y-%m-%d' '%H:%M:%S)] $1"
}

# read arguments
for ARG in $@
do
    case "$1" in
        -h|--help) usage; ;;
        --sns-topic) SNS_TOPIC=$2; shift 2; ;;
        # *) shift; ;;
    esac
done

if [ $# -lt 3 ]; then usage; fi

DOMAIN=$1
PORT=$2
SG_ID=$3

SNS_SUBJECT="Allow ${DOMAIN}:${PORT} outbound ${SG_ID}"

allow_ip () {
    CIDR="${1}/32"
    e "Querying AWS for ${CIDR} port ${PORT} in security group ${SG_ID} "
    if aws ec2 describe-security-groups --group-ids ${SG_ID} --query 'SecurityGroups[*].IpPermissionsEgress[?FromPort==`'"${PORT}"'`].IpRanges' --output text | grep ${CIDR}
    then
        e "Allow rule is already there."
        SNS_SUBJECT="${SNS_SUBJECT} - ${CIDR} already exists"
    else
        e "Allow rule is not there yet. Adding it now..."
        aws ec2 authorize-security-group-egress --group-id ${SG_ID} --ip-permissions '[{"IpProtocol": "tcp", "FromPort": '"${PORT}"', "ToPort": '"${PORT}"', "IpRanges": [{"CidrIp": "'"${CIDR}"'"}]}]'
        SNS_SUBJECT="${SNS_SUBJECT} - new IP ${CIDR} is added"
        if [ ! -z ${SNS_TOPIC} ]; then
            e "Sending SNS notification"
            aws sns publish --subject "${SNS_SUBJECT}" --message "${SNS_SUBJECT}" --topic-arn ${SNS_TOPIC}
        fi
    fi
}

e "Performing nsLookup for ${DOMAIN}"
nslookup ${DOMAIN} | awk '/^Address: / { print $2 }' | while read IP
do
    allow_ip $IP
    e ;
done